options:
  passphrase:
    type: string
    default: password123
    description: |
      Passphrase used to open the admin_operator.pfx certificate
  domain:
    type: string
    default:
    description: Orchestrator domain.
