feg-control-proxy:
  controller-key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCmWbDJc6L/QuPD
    DHss8K/fFPYRnWeArIGUafyIP5iDHKcyvjoqLCFLwxuPRYKju3Hd1NkC1NR3+n51
    +amqmGG/Wer+KbmDeUAx4hB3xyBS1wmqumIVC+ivUGbWoXpjWrikDgQ7HIOF6OMt
    W1yfTFhnEHsFhNGnUv1krSq/993AKzRNDCq45tKIwhDG+4YScLDl03QFSepnSO4F
    RAUxPZndEVI3HS9clb7jPXQ3DPgPR9FSRdWfpOta78zeiy8YuM2qZhDqjBXbBCU7
    LlvlxR9rW9xLRuuFJ3cTvD1+FjBcAPju+EWOdy5v2Sc1qFlFLNIt9QH7UzMAM0Jb
    H07BMmlNAgMBAAECggEACubwgKUALWvtvGZwtJD9N1WxPy9KZyYnHRoJgsgHaUeM
    wUHmH8YIbcwwKrNOBm5uKuRcgpexnKYnxcVigSH/SfvZ737xjKdhW/bD+7pq2//O
    2OF7mx1Olx37ipzgbGseLbywOn8gZlUzsLdlOkvV58J7PyQ/KN2pNxqbciOLy21b
    L7Vqx8S6uJw7YxZo7B+FZtJB2dcB3SYg6vjqb3Vc4fViowxtM7/b+o1xaWj+erdB
    VCaOjj0OfDLbdtsPuWRXrqr5uAe1o0n3tKj+0NtKN8QkkB287oyrzWbR1lz3JUV8
    Qck+IAUIbguEnLh1t/qQJUU6m3hwZC7w1ASi4WFH+wKBgQDTR4lPFq2WjqK4eF6H
    QfWz0aMA1nx58sVG1TGKc3ViP6exe4plAEqKj7HNP+bkLPtFuldmplUI+ooJDU5s
    fskjfasjflsajfdlksafjslkdjfslkñdjfsklñfjsakldjfsñdlfkjdlfkñjdñfl
    D46lLPfO8/3JUBJRuwEhhoCwjZ4W2SL85qM+oiZkawmaL7w2AFZUYrMyIHJ5V9mz
    v4Ko3FUmDBDXr3+wA8zlwT3DnwKBgQDJj5xTrjiV0ee/Y5NkjGZGb3q3eE0btugC
    H6xnOpo2nkXWLrddndvxMewahSn7dtCxp83xkeHwheESyk9aaWzZag/y7fEJ9ebL
    RJRrdsAfUSJ5dGlCXKSu27NrqBd+T81MQLSmlhTjMeIHm6rrFpWDd1GboRHJ5R3R
    pEh+CeTLkwKBgC1IIbefpqij/WAH/EqE6oIVphfh4F/KllluC+YehMP/3JL/ZVPs
    Ug2MapEQ5w10To5NN7o6X/NCrx7tiSdD1lC0aJAkXvosfSCjMcTbrO0qDP3cn9EQ
    JWChJBVVk4NGQ9JXFCmV1c4igiZbm78YhopmXqF+6IUxie5RgjKjzfcFAoGAAbmx
    ++Fk6JtoYXIHw/eTtIylv0ZPWqphKAt/XU7aHReTv3ac6Tc9t73WqI91QYrN1Id8
    MtIt3fI3cAK9VSfL37yRsGGrC4vIUvseTiExGdOG+QUvFXtXiYul6IkC0nj6Z+mx
    4i8stJkrtyb0+pgx5XMzBqMFVPYaID5IxJNvGvMCgYArErAAIBwNOsk9fVCQyibV
    tkCYxvWShHmML+6RB38vGUM7ffJ8AdcJ3mXAc+12vmPoR3MgBR3tobJlmUgxhAaz
    sdYPx7V9sku5Wu+InJ5tSi/hZi2I9Pilb5gymdPoGBDGAZnUwvFv4EVQQhPIS4uw
    GaWLKzzBpnmGMXfIAjwsMg==
    -----END PRIVATE KEY-----
  controller-crt: |-
    -----BEGIN CERTIFICATE-----
    MIIDnTCCAoWgAwIBAgIUGlm3wXnLUA/o4F4b/jr17cgeOKwwDQYJKoZIhvcNAQEL
    BQAwLTELMAkGA1UEBhMCVVMxHjAcBgNVBAMMFXJvb3RjYS55b3VyZG9tYWluLmNv
    bTAeFw0yMjA3MDYxNTIwMjhaFw0yNDEwMDgxNTIwMjhaMCgxCzAJBgNVBAYTAlVT
    MRkwFwYDVQQDDBAqLnlvdXJkb21haW4uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAplmwyXOi/0Ljwwx7LPCv3xT2EZ1ngKyBlGn8iD+YgxynMr46
    KiwhS8Mbj0WCo7tx3dTZAtTUd/p+dfmpqphhv1nq/im5g3lAMeIQd8cgUtcJqrpi
    FQvor1Bm1qF6Y1q4pA4EOxyDhejjLVtcn0xYZxB7BYTRp1L9ZK0qv/fdwCs0TQwq
    uObSiMIQxvuGEnCw5dN0BUnqZ0juBUQFMT2Z3RFSNx0vXJW+4z10Nwz4D0fRUkXV
    n6TrWu/M3osvGLjNqmYQ6owV2wQlOy5b5cUfa1vcS0brhSd3E7w9fhYwXAD47vhF
    jncub9knNahZRSzSLfUB+1MzADNCWx9OwTJpTQIDAQABo4G5MIG2MAkGA1UdEwQC
    MAAwaQYDVR0RBGIwYIIQKi55b3VyZG9tYWluLmNvbYIUKi5ubXMueW91cmRvbWFp
    bi5jb22CGCouc3RhZ2luZy55b3VyZG9tYWluLmNvbYIcKi5ubXMuc3RhZ2luZy55
    b3VyZG9tYWluLmNvbTAdBgNVHQ4EFgQUxzl/AEaI47LsJwnJINk4ZLOZcNswHwYD
    VR0jBBgwFoAUdugseduwNkBJ7heZf2DxrttqAUMwDQYJKoZIhvcNAQELBQADggEB
    AACEEv0giGxus/Bwtnb3pGKa5mu7bQPamT0DhBq6qwl8xPp6dP93tDJaF8QaKHMq
    54TvOPTWLFVOMJQZJDlBVyEjB8NrQeiZZiXPVgPTyiT5DmArO5fCsqB7JvPZqM2K
    fd1ftXRpxKxzTNzpLUvcjbkLuaAlXaEUU/bu5XSYhUxxcDdCoxlVoBE3rNJOCAdX
    QIRYjBWEvjWyX5ZT1oNIJK2QO+dbafwpXWs6WITt5BPO9k/sbkBJhA8ztxofEBr0
    EANWJ/0DpvCzOqbdsBDYpceQjbTwYl9lMLP+3b8TC52E/dseEmKlHahF+K6dlp99
    UBwM4xo+z6onwTr+vUfXNHI=
    -----END CERTIFICATE-----
  root-ca-key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpgIBAAKCAQEA750w9ImdIJqtCVYyqNQoolE2b9DamOCWFbxNsmgk4o6SOliM
    bejhva0kxUeU23yKTgshzmapiC2EUvgvUzEbJs40XwdtB1m0NRagiLy87XOxle9K
    0oHsHihBzKAdD31PA27cyaPamgfV8DDl9kxRA1MpJa0r4TNOZoEOqAiaPbsXo4Sb
    prsQd0zAbVfJz5X05gvdooCOn7+JT6jGdwLd3Ziuhy75bWonlOw+rlR/bZHdKa/5
    cpyYVGk9y75NL7iEUAq0ZwxZ0Hd6NNxa9/2EZ+WGw7x+GcSQu7JmczN/nZUMi8LU
    F1pinXJqGhcXWB4FxYk1+9OlIB6ScgDkBpfC+wIDAQABAoIBAQDBuqrJG7ZBlS1P
    /jRJUfdkfRrxPsBumC5gdnWvSAqCblkF+W/YsVBKpgGzy1MsPj4oKVH06gYpxvtU
    hbrlnS9hqZioOH3LUpijz56Nz2NE7KRpICazmj3IiC3i/pVgX6URloHGOcdVf/5W
    C4LyJvPdJ1B+WMvAcVXzBGdQLlxeiSRW4USdHkghRhhTyl89bUoTFwzKZMQEQIVM
    JxRE3RxEJ/AHypo0s144wqgiODcZtYGdZDHVBkoELTvSItm7OET12PVbXPJUdNoq
    siVmi6XeSnAoembGmI6V0trFDVfuVKjR31nLNKC/gVwLxDFynwr3zfO7ktOvjCWy
    L6m6jplJAoGBAP0E50sjHK8UvpBS8ceLv+0IHMXfUNsuZm5dUj91XFWsdHOOO9qA
    eBTeE331J51RtGnTiANAlPxGxMDdiWfn5aGRHFyKIpqTyTDdhixmwTAZUnTnZTek
    vJfHQUXCSBS9x0dAE5vXeKsqcQDJqoBTAsDq0aEA6fG9zQH587w9ETPvAoGBAPJv
    274+D9gR4A61jzrgCp4o0xEMrbJExqsivx1qw887L1ntqlYPSzyJ8I18unNa1FPM
    PtZRJKfVsuejpoQD120lERC4K0RKhtIhEvA5iomgUx6Z+Dn0HS5r/L8n4IwGG+D3
    mTC1vHeIy2OeCztcKl52HSKEe8phLKRM1UCDW6W1AoGBALC0Xfxht0SnTjdpViYw
    eYfHJKEkx0lr7Gmjjy92fVfwKxwQ98gv9K1OM3rCXjpGt6M48kKjNenCWuL/VVlV
    4U+nEpGmf2hJUjdoXq5fzQgUhzvR5ySnTncJ15Iqj0C9EZG3NHqgT0vrRiRwsz0P
    vFqTJHg3NSt5jNWWhRyv4XXNAoGBALzjBA1MI2IQQ0aSlL6lUgB6BECzZR2Q0k0B
    7G9KALeUAEeLkXwtvEu1mVNTS52Wtfl4F7k5TVrqd9JcQd93cr/Z8lrZcvRpMHPF
    SxEZc+PYowojoi/dD2NcxXZV5nCSTeRQZO17mxRy4yyBNXURUP15/ycmm6BJZ9O2
    /SufbKdFAoGBAIi8mPhySEhZjpETzAPGschIGBS9OKSiRgBJa6FcVx1P3JWLgZgI
    zyBBF81MLRlkOl+za36LuvNLqMzRqIPaoCZ/JV7iAOI1y/ieNK2RDJ4uCoeaHl7N
    b5asDMHVLQAU8EtxNstGz6Oq/IQOYpsPeQAYCM9JSG51llCxbEI+vJzd
    -----END RSA PRIVATE KEY-----
  root-ca-pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDNTCCAh2gAwIBAgIUO+L0oI3oKIOYjRl+ApKbU69MoWAwDQYJKoZIhvcNAQEL
    BQAwKjELMAkGA1UEBhMCVVMxGzAZBgNVBAMMEnJvb3RjYS5leGFtcGxlLmNvbTAe
    Fw0yMjA4MDkxMzE1MTlaFw0zMjA4MDYxMzE1MTlaMCoxCzAJBgNVBAYTAlVTMRsw
    GQYDVQQDDBJyb290Y2EuZXhhbXBsZS5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IB
    DwAwggEKAoIBAQDvnTD0iZ0gmq0JVjKo1CiiUTZv0NqY4JYVvE2yaCTijpI6WIxt
    6OG9rSTFR5TbfIpOCyHOZqmILYRS+C9TMRsmzjRfB20HWbQ1FqCIvLztc7GV70rS
    geweKEHMoB0PfU8DbtzJo9qaB9XwMOX2TFEDUyklrSvhM05mgQ6oCJo9uxejhJum
    uxB3TMBtV8nPlfTmC92igI6fv4lPqMZ3At3dmK6HLvltaieU7D6uVH9tkd0pr/ly
    nJhUaT3Lvk0vuIRQCrRnDFnQd3o03Fr3/YRn5YbDvH4ZxJC7smZzM3+dlQyLwtQX
    WmKdcmoaFxdYHgXFiTX706UgHpJyAOQGl8L7AgMBAAGjUzBRMB0GA1UdDgQWBBT2
    mj24adbxnm9f8XKl0MaQnMGxcDAfBgNVHSMEGDAWgBT2mj24adbxnm9f8XKl0MaQ
    nMGxcDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAUPZRoXTTF
    dlSkzLBk03zFKeoDDHUkIU8IBLxMfWzBV9w7FciVP916tTUA6M9mz0oJxUlhaE4D
    5uhDzTYTykqeGtLv+g4DNCqRlF+25MH0/FU+ogeSRWaP92nD0/OLVjkA7qyrvH2I
    TwS80ZrQp877+ZtBRafQGe0wwYWMTtQuvt25LUuMgbWUHDgVcw7Y4sB8QQJZS9Cg
    6Np9aRQIjtMUcoydgNCCTPVKlxiwdmbkokwi3DyyT+d/YFNEuaa658rFxFT4XliG
    DWwSIQJNauiUmUgqlXn/ilO93gKsWaZNbDN/kHHnByV012QMGIpHa1Ftecqw3tsZ
    M7Hmy1yppiDd
    -----END CERTIFICATE-----
