options:
  domain:
    type: string
    default:
    description: Fluentd domain
  elasticsearch-url:
    type: string
    default:
    description: |
      ElasticSearch URL (example: orc8r-elasticsearch:9200)
  fluentd-chunk-limit-size:
    type: string
    default: 2M
    description: |
      The size limit of the received chunk. If the chunk size is larger than this value, 
      the received chunk is dropped.
  fluentd-queue-limit-length:
    type: int
    default: 8
    description: |
      The limit of the chunk queue length. If the chunk queue length is larger than this value,
      the received chunk is dropped.
