name: Upload orc8r-bundle

on:
  push:
    branches:
      - "1.8"
    paths:
      - "orc8r-bundle/**"

jobs:
  orc8r-bundle-charmhub-upload:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'

      - name: install jinja2
        run: pip install -U Jinja2==$JINJA_VERSION

      - name: render bundle.yaml
        run: |
          python orc8r-bundle/render_bundle.py \
          --template orc8r-bundle/bundle.yaml.j2 --output orc8r-bundle/bundle.yaml --channel 1.8/edge

      - name: copy README.md
        run: |
          cp README.md orc8r-bundle/

      - name: Upload bundle
        uses: canonical/charming-actions/upload-bundle@1.0.2
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          bundle-path: ./orc8r-bundle
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          channel: 1.8/edge
