name: orc8r-configurator

on:
  push:
    paths:
      - "orc8r-configurator-operator/**"

jobs:
  orc8r-configurator-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-configurator-operator

  orc8r-configurator-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-configurator-operator

  orc8r-configurator-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-configurator-operator

  orc8r-configurator-integration-test:
    name: Integration tests
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-configurator-operator

  orc8r-configurator-charmhub-upload:
    if: github.ref_name == '1.6'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-configurator-operator
