name: orc8r-ctraced

on:
  push:
    paths:
      - "orc8r-ctraced-operator/**"

jobs:
  orc8r-ctraced-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-ctraced-operator

  orc8r-ctraced-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-ctraced-operator

  orc8r-ctraced-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-ctraced-operator

  orc8r-ctraced-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-ctraced-operator

  orc8r-ctraced-charmhub-upload:
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-ctraced-operator
