name: orc8r-device

on:
  push:
    paths:
      - "orc8r-device-operator/**"

jobs:
  orc8r-device-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-device-operator

  orc8r-device-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-device-operator

  orc8r-device-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-device-operator

  orc8r-device-integration-test:
    name: Integration tests
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-device-operator

  orc8r-device-charmhub-upload:
    if: github.ref_name == '1.6'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-device-operator
