name: orc8r-eventd

on:
  push:
    paths:
      - "orc8r-eventd-operator/**"

jobs:
  orc8r-eventd-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-eventd-operator

  orc8r-eventd-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-eventd-operator

  orc8r-eventd-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-eventd-operator

  orc8r-eventd-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-eventd-operator

  orc8r-eventd-charmhub-upload:
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-eventd-operator
