name: orc8r-feg-relay

on:
  push:
    paths:
      - "orc8r-feg-relay-operator/**"

jobs:
  orc8r-feg-relay-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-feg-relay-operator

  orc8r-feg-relay-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-feg-relay-operator

  orc8r-feg-relay-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-feg-relay-operator

  orc8r-feg-relay-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-feg-relay-operator

  orc8r-feg-relay-charmhub-upload:
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-feg-relay-operator
