name: Integration Tests

on:
  workflow_call:
    inputs:
      charm_dir:
        required: true
        type: string

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: |
      echo "Microk8s version: ${{ env.MICROK8S_VERSION }}"
      echo "Juju version: ${{ env.JUJU_VERSION }}"

      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: ${{ env.MICROK8S_VERSION }}
          juju-channel: ${{ env.JUJU_VERSION }}
          juju-crashdump-channel: latest/stable
      - name: Run integration tests
        run: cd ${{ inputs.charm_dir }} && tox -e integration
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-logs
          path: /home/runner/.local/state/charmcraft/log/*.log
      - name: Archive juju crashdump
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: juju-crashdump
          path: ${{ inputs.charm_dir }}/juju-crashdump-*.tar.xz
