name: Integration Tests

on:
  workflow_call:
    inputs:
      charm_dir:
        required: true
        type: string

jobs:
  integration-tests:
    name: Integration tests for ${{ inputs.charm_dir }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          juju-channel: $JUJU_CHANNEL
      - name: Run integration tests
        run: cd ${{ inputs.charm_dir }} && tox -e integration
      - name: Archive charmcraft logs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: charmcraft-logs
          path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/*.log
