name: orc8r-libs

on:
  push:
    paths:
      - 'orc8r-libs/**'

jobs:
  orc8r-libs-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-libs

  orc8r-libs-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-libs

  orc8r-libs-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-libs

  orc8r-libs-charms-charmhub-upload:
    if: github.ref_name == '1.6'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-libs

  orc8r-libs-charmhub-upload:
    if: github.ref_name == '1.6'
    uses: ./.github/workflows/upload-libs.yml
    secrets: inherit
    with:
      charm: orc8r-libs
      libs: "charms.magma_orc8r_libs.v0.orc8r_base charms.magma_orc8r_libs.v0.orc8r_base_db"
