name: 1.8

on:
  pull_request:
    branches:
      - 1.8
  push:
    branches:
      - 1.8
  schedule:
    - cron: "0 0 * * *"

jobs:
  orchestrator-lint-report:
    name: Lint report
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: |
          set -eux
          charms="$(find ./ -name tox.ini)"
          for charm in ${charms}; do
            tox -c "${charm}" -e lint
          done

  orchestrator-static-analysis:
    name: Static analysis
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: |
          set -eux
          charms="$(find ./ -name tox.ini)"
          for charm in ${charms}; do
            tox -c "${charm}" -e static
          done

  orchestrator-unit-tests-with-coverage:
    name: Unit tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@v0.2
        with:
          varFilePath: ./.github/variables/dependencies_versions.env
      - name: Install tox
        run: pip install tox==$TOX_VERSION
      - name: Run tests using tox
        run: |
          set -eux
          charms="$(find ./ -name tox.ini  -not -path "./orc8r-bundle/*")"
          for charm in ${charms}; do
            tox -c "${charm}" -e unit
          done

  orchestrator-integration-test:
    name: Integration tests
    uses: ./.github/workflows/integration-tests-self-hosted.yml
    with:
      charm_dir: orc8r-bundle
