name: orc8r-nginx

on:
  push:
    paths:
      - "orc8r-nginx-operator/**"

jobs:
  orc8r-nginx-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-nginx-operator

  orc8r-nginx-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-nginx-operator

  orc8r-nginx-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-nginx-operator

  orc8r-nginx-integration-test:
    name: Integration tests
    uses: ./.github/workflows/integration-tests-self-hosted.yml
    with:
      charm_dir: orc8r-nginx-operator

  orc8r-nginx-charmhub-upload:
    if: github.ref_name == '1.6'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-nginx-operator
