name: nms-magmalte

on:
  push:
    paths:
      - "nms-magmalte-operator/**"

jobs:
  nms-magmalte-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: nms-magmalte-operator

  nms-magmalte-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: nms-magmalte-operator

  nms-magmalte-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: nms-magmalte-operator

  nms-magmalte-integration-test:
    uses: ./.github/workflows/integration-tests-self-hosted.yml
    with:
      charm_dir: nms-magmalte-operator

  nms-magmalte-charmhub-upload:
    if: github.ref_name == '1.6'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: nms-magmalte-operator
