name: orc8r-orchestrator

on:
  push:
    paths:
      - "orchestrator-bundle/orc8r-orchestrator-operator/**"

jobs:
  orc8r-orchestrator-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-orchestrator-operator

  orc8r-orchestrator-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-orchestrator-operator

  orc8r-orchestrator-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-orchestrator-operator

  orc8r-orchestrator-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-orchestrator-operator

  orc8r-orchestrator-charmhub-upload:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-orchestrator
