name: orc8r-subscriberdb

on:
  push:
    paths:
      - "orchestrator-bundle/orc8r-subscriberdb-operator/**"

jobs:
  orc8r-subscriberdb-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-subscriberdb-operator

  orc8r-subscriberdb-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-subscriberdb-operator

  orc8r-subscriberdb-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-subscriberdb-operator

  orc8r-subscriberdb-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-subscriberdb-operator

  orc8r-subscriberdb-charmhub-upload:
    if: github.ref_name == "main"
    uses: ./.github/workflows/upload-charm.yml
    with:
      charm: orc8r-subscriberdb
