name: orc8r-obsidian

on:
  push:
    paths:
      - "orchestrator-bundle/orc8r-obsidian-operator/**"

jobs:
  orc8r-obsidian-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-obsidian-operator

  orc8r-obsidian-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-obsidian-operator

  orc8r-obsidian-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-obsidian-operator

  orc8r-obsidian-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-obsidian-operator

  orc8r-obsidian-charmhub-upload:
    if: github.ref_name == "main"
    uses: ./.github/workflows/upload-charm.yml
    with:
      charm: orc8r-obsidian
