name: Upload orc8r-libs

on:
  push:
    branches:
      - "main"
    paths:
      - "orchestrator-bundle/orc8r-libs/**"

jobs:
  orc8r-libs-charmhub-upload:
    runs-on: ubuntu-20.04
    name: Charmhub upload orc8r-libs
    steps:
      - uses: actions/checkout@v2

      - uses: canonical/charmhub-upload-action@0.2.1
        with:
          credentials: "${{ secrets.CHARMCRAFT_AUTH }}"
          charm-path: ./orchestrator-bundle/orc8r-libs
          upload-image: "false"

      - name: Publish libs
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMCRAFT_AUTH }}"
        run: |
          set -eux
          orc8r_libs="
          charms.magma_orc8r_libs.v0.orc8r_base 
          charms.magma_orc8r_libs.v0.orc8r_base_db
          "
          for lib in ${orc8r_libs}; do
            echo "Publishing ${lib}"
            (cd ./orchestrator-bundle/orc8r-libs && charmcraft publish-lib ${lib})
          done
