name: Static Analysis

on:
  workflow_call:
    inputs:
      charm_dir:
        required: true
        type: string

jobs:
  static-analysis:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install tox
        run: pip install tox
      - name: Run tests using tox
        run: cd ${{ inputs.charm_dir }} && tox -e static
