name: orc8r-subscriberdb-cache

on:
  push:
    paths:
      - "orc8r-subscriberdb-cache-operator/**"

jobs:
  orc8r-subscriberdb-cache-lint-report:
    uses: ./.github/workflows/lint-report.yml
    with:
      charm_dir: orc8r-subscriberdb-cache-operator

  orc8r-subscriberdb-cache-static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      charm_dir: orc8r-subscriberdb-cache-operator

  orc8r-subscriberdb-cache-unit-tests-with-coverage:
    uses: ./.github/workflows/unit-tests.yml
    with:
      charm_dir: orc8r-subscriberdb-cache-operator

  orc8r-subscriberdb-cache-integration-test:
    uses: ./.github/workflows/integration-tests.yml
    with:
      charm_dir: orc8r-subscriberdb-cache-operator

  orc8r-subscriberdb-cache-charmhub-upload:
    uses: ./.github/workflows/upload-charm.yml
    secrets: inherit
    with:
      charm: orc8r-subscriberdb-cache-operator
